# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewPrincipal.Ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Principal(object):
    def setupUi(self, Principal):
        Principal.setObjectName("Principal")
        Principal.resize(554, 431)
        Principal.setStyleSheet("background-color: rgba(18,18,18,1);")
        self.centralwidget = QtWidgets.QWidget(Principal)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setKerning(False)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: rgba(18,18,18,1);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.buttonResultados = QtWidgets.QPushButton(self.frame)
        self.buttonResultados.setGeometry(QtCore.QRect(180, 370, 121, 21))
        self.buttonResultados.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonResultados.setStyleSheet("background-color: rgba(30, 215, 96,0.65);\n"
"color: white;\n"
"font:bold;\n"
"\n"
"")
        self.buttonResultados.setCheckable(False)
        self.buttonResultados.setChecked(False)
        self.buttonResultados.setDefault(True)
        self.buttonResultados.setFlat(False)
        self.buttonResultados.setObjectName("buttonResultados")
        self.TextFieldPath = QtWidgets.QLineEdit(self.frame)
        self.TextFieldPath.setEnabled(False)
        self.TextFieldPath.setGeometry(QtCore.QRect(10, 10, 301, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.TextFieldPath.setFont(font)
        self.TextFieldPath.setStyleSheet("border:1px;\n"
"background-color : white;\n"
"color:Black;")
        self.TextFieldPath.setText("")
        self.TextFieldPath.setPlaceholderText("")
        self.TextFieldPath.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.TextFieldPath.setObjectName("TextFieldPath")
        self.ElegirArchivo = QtWidgets.QPushButton(self.frame)
        self.ElegirArchivo.setGeometry(QtCore.QRect(320, 10, 121, 21))
        self.ElegirArchivo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ElegirArchivo.setStyleSheet("background-color: rgba(30, 215, 96,0.65);\n"
"color: white;\n"
"font:bold;\n"
"\n"
"")
        self.ElegirArchivo.setCheckable(False)
        self.ElegirArchivo.setChecked(False)
        self.ElegirArchivo.setDefault(True)
        self.ElegirArchivo.setFlat(False)
        self.ElegirArchivo.setObjectName("ElegirArchivo")
        self.tableDiscretos = QtWidgets.QTableWidget(self.frame)
        self.tableDiscretos.setGeometry(QtCore.QRect(20, 50, 151, 291))
        self.tableDiscretos.setStyleSheet("background-color: rgb(198, 198, 198);\n"
"color: rgb(50, 50, 50);")
        self.tableDiscretos.setObjectName("tableDiscretos")
        self.tableDiscretos.setColumnCount(1)
        self.tableDiscretos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableDiscretos.setHorizontalHeaderItem(0, item)
        self.tableDiscretos.horizontalHeader().setDefaultSectionSize(150)
        self.tableContinuos = QtWidgets.QTableWidget(self.frame)
        self.tableContinuos.setGeometry(QtCore.QRect(190, 50, 151, 291))
        self.tableContinuos.setStyleSheet("background-color: rgb(198, 198, 198);\n"
"color: rgb(50, 50, 50);")
        self.tableContinuos.setObjectName("tableContinuos")
        self.tableContinuos.setColumnCount(1)
        self.tableContinuos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableContinuos.setHorizontalHeaderItem(0, item)
        self.tableContinuos.horizontalHeader().setDefaultSectionSize(150)
        self.tableCualitativos = QtWidgets.QTableWidget(self.frame)
        self.tableCualitativos.setGeometry(QtCore.QRect(360, 50, 151, 291))
        self.tableCualitativos.setStyleSheet("background-color: rgb(198, 198, 198);\n"
"color: rgb(50, 50, 50);")
        self.tableCualitativos.setObjectName("tableCualitativos")
        self.tableCualitativos.setColumnCount(1)
        self.tableCualitativos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableCualitativos.setHorizontalHeaderItem(0, item)
        self.tableCualitativos.horizontalHeader().setVisible(True)
        self.tableCualitativos.horizontalHeader().setCascadingSectionResizes(True)
        self.tableCualitativos.horizontalHeader().setDefaultSectionSize(150)
        self.horizontalLayout.addWidget(self.frame)
        Principal.setCentralWidget(self.centralwidget)

        self.retranslateUi(Principal)
        QtCore.QMetaObject.connectSlotsByName(Principal)

    def retranslateUi(self, Principal):
        _translate = QtCore.QCoreApplication.translate
        Principal.setWindowTitle(_translate("Principal", "Probabilidad_Estaditica"))
        self.buttonResultados.setText(_translate("Principal", "Generar Resultados"))
        self.ElegirArchivo.setText(_translate("Principal", "Elegir Archivo"))
        item = self.tableDiscretos.horizontalHeaderItem(0)
        item.setText(_translate("Principal", "Valores Discretos"))
        item = self.tableContinuos.horizontalHeaderItem(0)
        item.setText(_translate("Principal", "Valores Continuos"))
        item = self.tableCualitativos.horizontalHeaderItem(0)
        item.setText(_translate("Principal", "Valores Cualitativos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Principal = QtWidgets.QMainWindow()
    ui = Ui_Principal()
    ui.setupUi(Principal)
    Principal.show()
    sys.exit(app.exec_())
