# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewPrincipal.Ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Principal(object):
    def setupUi(self, Principal):
        Principal.setObjectName("Principal")
        Principal.setEnabled(True)
        Principal.resize(514, 431)
        Principal.setStyleSheet("background-color: rgba(18,18,18,1);")
        self.centralwidget = QtWidgets.QWidget(Principal)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        font = QtGui.QFont()
        font.setKerning(False)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: rgba(18,18,18,1);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.buttonDiscretos = QtWidgets.QPushButton(self.frame)
        self.buttonDiscretos.setGeometry(QtCore.QRect(20, 360, 125, 31))
        self.buttonDiscretos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonDiscretos.setStyleSheet("background-color: rgba(30, 215, 96,0.65);\n"
"color: white;\n"
"font:bold;\n"
"\n"
"")
        self.buttonDiscretos.setCheckable(False)
        self.buttonDiscretos.setChecked(False)
        self.buttonDiscretos.setDefault(True)
        self.buttonDiscretos.setFlat(False)
        self.buttonDiscretos.setObjectName("buttonDiscretos")
        self.TextFieldPath = QtWidgets.QLineEdit(self.frame)
        self.TextFieldPath.setEnabled(False)
        self.TextFieldPath.setGeometry(QtCore.QRect(20, 10, 301, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.TextFieldPath.setFont(font)
        self.TextFieldPath.setStyleSheet("border:1px;\n"
"background-color : white;\n"
"color:Black;")
        self.TextFieldPath.setText("")
        self.TextFieldPath.setPlaceholderText("")
        self.TextFieldPath.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.TextFieldPath.setObjectName("TextFieldPath")
        self.ElegirArchivo = QtWidgets.QPushButton(self.frame)
        self.ElegirArchivo.setGeometry(QtCore.QRect(350, 10, 121, 21))
        self.ElegirArchivo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ElegirArchivo.setStyleSheet("background-color: rgba(30, 215, 96,0.65);\n"
"color: white;\n"
"font:bold;\n"
"\n"
"")
        self.ElegirArchivo.setCheckable(False)
        self.ElegirArchivo.setChecked(False)
        self.ElegirArchivo.setDefault(True)
        self.ElegirArchivo.setFlat(False)
        self.ElegirArchivo.setObjectName("ElegirArchivo")
        self.tableDiscretos = QtWidgets.QTableWidget(self.frame)
        self.tableDiscretos.setGeometry(QtCore.QRect(20, 50, 125, 291))
        self.tableDiscretos.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableDiscretos.setAutoFillBackground(True)
        self.tableDiscretos.setStyleSheet("background-color: rgb(198, 198, 198);\n"
"color: rgb(50, 50, 50);")
        self.tableDiscretos.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableDiscretos.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableDiscretos.setAutoScroll(True)
        self.tableDiscretos.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableDiscretos.setDragEnabled(False)
        self.tableDiscretos.setAlternatingRowColors(False)
        self.tableDiscretos.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tableDiscretos.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableDiscretos.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableDiscretos.setGridStyle(QtCore.Qt.SolidLine)
        self.tableDiscretos.setRowCount(0)
        self.tableDiscretos.setObjectName("tableDiscretos")
        self.tableDiscretos.setColumnCount(1)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableDiscretos.setHorizontalHeaderItem(0, item)
        self.tableDiscretos.horizontalHeader().setVisible(True)
        self.tableDiscretos.horizontalHeader().setCascadingSectionResizes(False)
        self.tableDiscretos.horizontalHeader().setDefaultSectionSize(100)
        self.tableDiscretos.horizontalHeader().setHighlightSections(False)
        self.tableDiscretos.horizontalHeader().setMinimumSectionSize(10)
        self.tableDiscretos.horizontalHeader().setSortIndicatorShown(False)
        self.tableDiscretos.horizontalHeader().setStretchLastSection(True)
        self.tableDiscretos.verticalHeader().setVisible(True)
        self.tableDiscretos.verticalHeader().setCascadingSectionResizes(True)
        self.tableDiscretos.verticalHeader().setDefaultSectionSize(25)
        self.tableDiscretos.verticalHeader().setHighlightSections(True)
        self.tableDiscretos.verticalHeader().setMinimumSectionSize(10)
        self.tableDiscretos.verticalHeader().setSortIndicatorShown(True)
        self.tableDiscretos.verticalHeader().setStretchLastSection(False)
        self.tableContinuos = QtWidgets.QTableWidget(self.frame)
        self.tableContinuos.setGeometry(QtCore.QRect(170, 50, 125, 291))
        self.tableContinuos.setStyleSheet("background-color: rgb(198, 198, 198);\n"
"color: rgb(50, 50, 50);")
        self.tableContinuos.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableContinuos.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableContinuos.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableContinuos.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableContinuos.setRowCount(0)
        self.tableContinuos.setObjectName("tableContinuos")
        self.tableContinuos.setColumnCount(1)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableContinuos.setHorizontalHeaderItem(0, item)
        self.tableContinuos.horizontalHeader().setCascadingSectionResizes(False)
        self.tableContinuos.horizontalHeader().setDefaultSectionSize(100)
        self.tableContinuos.horizontalHeader().setHighlightSections(False)
        self.tableContinuos.horizontalHeader().setMinimumSectionSize(10)
        self.tableContinuos.horizontalHeader().setSortIndicatorShown(False)
        self.tableContinuos.horizontalHeader().setStretchLastSection(True)
        self.tableContinuos.verticalHeader().setVisible(True)
        self.tableContinuos.verticalHeader().setCascadingSectionResizes(True)
        self.tableContinuos.verticalHeader().setDefaultSectionSize(25)
        self.tableContinuos.verticalHeader().setHighlightSections(True)
        self.tableContinuos.verticalHeader().setMinimumSectionSize(10)
        self.tableContinuos.verticalHeader().setSortIndicatorShown(True)
        self.tableContinuos.verticalHeader().setStretchLastSection(False)
        self.tableCualitativos = QtWidgets.QTableWidget(self.frame)
        self.tableCualitativos.setGeometry(QtCore.QRect(320, 50, 151, 291))
        self.tableCualitativos.setStyleSheet("background-color: rgb(198, 198, 198);\n"
"color: rgb(50, 50, 50);")
        self.tableCualitativos.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableCualitativos.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableCualitativos.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableCualitativos.setRowCount(0)
        self.tableCualitativos.setObjectName("tableCualitativos")
        self.tableCualitativos.setColumnCount(1)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableCualitativos.setHorizontalHeaderItem(0, item)
        self.tableCualitativos.horizontalHeader().setVisible(True)
        self.tableCualitativos.horizontalHeader().setCascadingSectionResizes(False)
        self.tableCualitativos.horizontalHeader().setDefaultSectionSize(125)
        self.tableCualitativos.horizontalHeader().setHighlightSections(False)
        self.tableCualitativos.horizontalHeader().setMinimumSectionSize(10)
        self.tableCualitativos.horizontalHeader().setSortIndicatorShown(False)
        self.tableCualitativos.horizontalHeader().setStretchLastSection(True)
        self.tableCualitativos.verticalHeader().setVisible(True)
        self.tableCualitativos.verticalHeader().setCascadingSectionResizes(True)
        self.tableCualitativos.verticalHeader().setDefaultSectionSize(25)
        self.tableCualitativos.verticalHeader().setHighlightSections(True)
        self.tableCualitativos.verticalHeader().setMinimumSectionSize(10)
        self.tableCualitativos.verticalHeader().setSortIndicatorShown(True)
        self.tableCualitativos.verticalHeader().setStretchLastSection(False)
        self.buttonContinuos = QtWidgets.QPushButton(self.frame)
        self.buttonContinuos.setGeometry(QtCore.QRect(170, 360, 125, 31))
        self.buttonContinuos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonContinuos.setStyleSheet("background-color: rgba(30, 215, 96,0.65);\n"
"color: white;\n"
"font:bold;\n"
"\n"
"")
        self.buttonContinuos.setCheckable(False)
        self.buttonContinuos.setChecked(False)
        self.buttonContinuos.setDefault(True)
        self.buttonContinuos.setFlat(False)
        self.buttonContinuos.setObjectName("buttonContinuos")
        self.buttonCualitativos = QtWidgets.QPushButton(self.frame)
        self.buttonCualitativos.setGeometry(QtCore.QRect(320, 360, 151, 31))
        self.buttonCualitativos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonCualitativos.setStyleSheet("background-color: rgba(30, 215, 96,0.65);\n"
"color: white;\n"
"font:bold;\n"
"\n"
"")
        self.buttonCualitativos.setCheckable(False)
        self.buttonCualitativos.setChecked(False)
        self.buttonCualitativos.setDefault(True)
        self.buttonCualitativos.setFlat(False)
        self.buttonCualitativos.setObjectName("buttonCualitativos")
        self.horizontalLayout.addWidget(self.frame)
        Principal.setCentralWidget(self.centralwidget)

        self.retranslateUi(Principal)
        QtCore.QMetaObject.connectSlotsByName(Principal)

    def retranslateUi(self, Principal):
        _translate = QtCore.QCoreApplication.translate
        Principal.setWindowTitle(_translate("Principal", "Probabilidad_Estaditica"))
        self.buttonDiscretos.setText(_translate("Principal", "Calculos Discretos"))
        self.ElegirArchivo.setText(_translate("Principal", "Elegir Archivo"))
        self.tableDiscretos.setSortingEnabled(False)
        item = self.tableDiscretos.horizontalHeaderItem(0)
        item.setText(_translate("Principal", "Discretos"))
        item = self.tableContinuos.horizontalHeaderItem(0)
        item.setText(_translate("Principal", "Continuos"))
        item = self.tableCualitativos.horizontalHeaderItem(0)
        item.setText(_translate("Principal", "Cualitativos"))
        self.buttonContinuos.setText(_translate("Principal", "Calculos Continuos"))
        self.buttonCualitativos.setText(_translate("Principal", "Calculos Cualitativos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Principal = QtWidgets.QMainWindow()
    ui = Ui_Principal()
    ui.setupUi(Principal)
    Principal.show()
    sys.exit(app.exec_())
